apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.deployment.name }}
    spec:
      containers:
      - name: {{ .Values.deployment.image.name }}
        image: {{ .Values.deployment.image.name }}:{{ .Values.deployment.image.tag }}
        ports:
        - containerPort: {{ .Values.service.port }}
        volumeMounts:
          - name: {{ .Values.configmap.name }}
            mountPath: /usr/share/nginx/html
      volumes:
        - name: {{ .Values.configmap.name }}
          configMap:
            name: {{ .Values.configmap.name }}
