apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.secret.name }}
    namespace: {{ .Release.Namespace }}
type: {{ .Values.secret.type }}
data:
  tls.key: |
{{ index .Values.secret "key" | nindent 4 }}
  tls.crt: |
{{ index .Values.secret "crt" | nindent 4 }}